name: Deploy Medusa Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 657506130511.dkr.ecr.ap-south-1.amazonaws.com

    - name: Build & Push Docker Image
      run: |
        docker build -t medusa -f docker/Dockerfile .
        docker tag medusa:latest 657506130511.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest
        docker push 657506130511.dkr.ecr.ap-south-1.amazonaws.com/medusa:latest

    - name: Update ECS Task Definition
      run: |
        aws ecs update-service \
          --cluster medusa-cluster \
          --service medusa-service \
          --force-new-deployment
# just for test